# Generated by Django 3.2.9 on 2021-11-21 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=50)),
                ('contraseña', models.CharField(max_length=20)),
            ],
        ),
    ]
